import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <div className="min-h-screen flex justify-center bg-zinc-50 font-sans dark:bg-black p-4">
            <div className="      
              w-full max-w-6xl 
              bg-white dark:bg-neutral-950 
              border border-neutral-200 
              shadow 
              overflow-hidden">
              <div className="p-6 sm:p-8">
                <Header></Header>
                <div className="      
         flex overflow-hidden 
          border border-neutral-300 
          bg-neutral-100 dark:bg-neutral-900
          text-neutral-800 dark:text-neutral-200">
                  {children}
                </div>
              </div>
            </div>
          </div>  
          </ThemeProvider>
      </body>
    </html>
  );
}
